---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sqlproxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "sqlproxy.name" . }}
    chart: {{ template "sqlproxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: {{ template "sqlproxy.name" . }}
    release: {{ .Release.Name }}
